version: "3.7"
services: 
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD='210023'
    networks:
      - network_aplication

  api:
    build: "./devtransacao"
    container_name: api-container
    restart: always
    ports: 
      - "9091:8080"
    networks: 
     - network_aplication
    environment: 
      - SPRING_PROFILES_ACTIVE=prod
      - DATASOURCE_URL=jdbc:mysql://db:3306/db?useTimezone=true&serverTimezone=UTC
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=210023

  web:
    build: "./Layout"
    container_name: pages-container
    restart: always
    ports:
      - "9090:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks: 
    - network_aplication

networks: 
  network_aplication:
   driver: bridge




